version: "3.1"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zerotier:
    image: zyclonite/zerotier:1.10.6
    hostname: zerotier
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - app-network
    ports:
      - "9993:9993"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29

  next_ztnet:
    image: sinamics/next_ztnet:latest
    container_name: ztnet
    platform: "linux/amd64"
    working_dir: /app
    volumes:
      - zerotier:/var/lib/zerotier-one:ro
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      ZT_ADDR: http://zerotier:9993
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      NEXTAUTH_URL: "http://localhost:3000" # change localhost to your domain or server ip address if hosting on a server.
      NEXTAUTH_SECRET: "random_secret" # change this to a random string of characters.
    networks:
      - app-network
    depends_on:
      - postgres
      - zerotier
  zeronsd:
    image: sinamics/zeronsd:latest
    container_name: zeronsd
    restart: unless-stopped
    network_mode: host
    # networks:
    #   - app-network
    command: "start e863ce852ff091d8 && cat /var/lib/zerotier-one/authtoken.secret"
    volumes:
      - zerotier:/var/lib/zerotier-one:ro
    # depends_on:
    #   - zerotier
    #   - next_ztnet
    environment:
      ZEROTIER_CENTRAL_INSTANCE: "http://127.0.0.1:3000/api/zeronsd"
      ZEROTIER_CENTRAL_TOKEN: "2p8v8twvfnqe90bke7vk70py"
      ZEROTIER_LOCAL_URL: http://127.0.0.1:9993

volumes:
  zerotier:
  postgres-data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
